### PR TITLE
Add `assert_raise`:

### PR DESCRIPTION
**Pull request by weakish**
assert_raise(SomeException) { code } #=> true
    assert_raise(AncestorExcepiton) { code } #=> true
    assert_raise(SomeException) { code } #=> 'Nothing raised!'
    assert_raise(SomeException) { code }
    #=> 'Got #<AnotherException: message> raised!'
    assert_raise(SomeException, AnotherException) { code } #=> true

### CODE REVIEW

**Comment by p0deje** [comment]
I've been thinking about handling exceptions as well, but for the different point of view.

For instance, I've been thinking about something like this:

```ruby
# @example
#   1 / 0 #=> raise ZeroDivisionError
#   1 / 0 #=> raise ZeroDivisionError, "divided by 0"
#   1 / 1 #=> 1
```

What do you think about this approach? I feel like it's more flexible and readable.

The reason I don't want to have any `assert_*` methods is because the doctest should not be only test, it should still be a documentation and example of usage. With that said, having some method that is only available in tests is bad, because this makes documentation less clear.

**Comment by p0deje** [comment]
I've added the approach suggested above, though it has some limitations:

1. You have to use the same message in expected value.
2. You have to pass message to expected value if actual is raised with message.
3. You have to use the same class of exception - ancestors won't work.

I'd like to hear your thoughts on this before releasing new version.

**Comment by weakish** [comment]
> 1. You have to use the same message in expected value.
> 2. You have to pass message to expected value if actual is raised with message.
> 3. You have to use the same class of exception - ancestors won't work.

3 is derived form 1 and there are two more limitations derived form 1:

4) Multiple exceptions won't work.
5) You can cheat by returning a string.

An example of 5:

```ruby
# @example
#   'raise ZeroDivisionError, "divided by 0"' #=> raise ZeroDivisionError, "divided by 0"
```

And the [current implementation][52] seems only handle `StandardError`:

```ruby
rescue StandardError => error
```

This brings in another limitation:

6) Exceptions beyond StandardError won't work.

For example:

```ruby
# @example
#   raise NotImplementedError  #=> raise NotImplementedError
```

For implementation simplicity and normal use cases, I think limitations 1-5 are acceptable.
But IMO limitation 6 is not necessary.

Why `rescue StandardError` instead of `rescue Exception`?
Is this because there are some exceptions yard-doctest may raise?
Then what about `rescue Exception` then test if `Exception` belongs to those preserved exceptions and need to be raise.

[52]: https://github.com/p0deje/yard-doctest/commit/2823f3d81f2792f4c3dc00384fa685e128d8ea9e#diff-77181c740c63abbd5237eb7be62d47dbR52

**Comment by p0deje** [comment]
There are two reasons to rescue `StandardError` and not `Exception:

1. It's default behavior when you use `rescue` without exception class. So, all custom error classes should extend it.
2. It's generally a [bad idea](http://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby) to rescue `Exception` (especially since we're not raising it after).

**Comment by p0deje** [comment]
> 4) Multiple exceptions won't work.

I'm not sure why it's needed it at all.

**Comment by weakish** [comment]
>> 4) Multiple exceptions won't work.
> I'm not sure why it's needed it at all.

minitest's `assert_raises` support this. I think it is rarely used, though.

> It's generally a bad idea to rescue Exception

I think it is acceptable in tests, since if an Exception raised and it is not expected, the test will fail after all. And `C-c` or `kill yard` still works. 

> if you have a documentation example which raises something that is not StandardError, your documentation example is unnecessary/incorrect and you should probably change it.

What about documenting/testing unimplemented feature?

**Comment by p0deje** [comment]
> What about documenting/testing unimplemented feature?

Can you give an example?

**Comment by weakish** [comment]
> Can you give an example?

> I also think that if you have a documentation example which raises something that is not StandardError, your documentation example is unnecessary

Hmm, when thinking an example I realized that for documentation just saying 'something is unimplemented' is clearer than giving a `NotImplementedError` example. 
The real reason was I sometimes wanted to test `NotImplementedError` will actually be triggered and were too lazy to write it in a separate test file.

**Comment by p0deje** [comment]
I suppose the usual case for `NotImplementedError` is creating interfaces, so a documentation example for it should probably be a class implementing it (in this case, no raises should be documented at all).

**Comment by p0deje** [comment]
Looks like it's settled so I'll probably make a release later today.

**Comment by weakish** [comment]
:+1:

**Comment by p0deje** [comment]
Released in 0.1.5.

**Pull request closed without merging**
